SDK/backendlessAPI/Classes/UserService/UserService.m
http://bugs.backendless.com/browse/BKNDLSS-14162
=> Async isValidUserToken fixed

SDK/backendlessAPI/Classes/UserService/UserService.h, SDK/backendlessAPI/Classes/UserService/UserService.m, SDK/ios/backendless/include/UserService.h, SDK/lib/backendless/include/UserService.h, SDK/osx/backendless/include/UserService.h
http://bugs.backendless.com/browse/BKNDLSS-14167
=> the user update method which takes IResponder argument removed

SDK/backendlessAPI/Classes/UserService/UserService.h, SDK/backendlessAPI/Classes/UserService/UserService.m, SDK/ios/backendless/include/UserService.h, SDK/lib/backendless/include/UserService.h, SDK/osx/backendless/include/UserService.h
http://bugs.backendless.com/browse/BKNDLSS-14169
=> the logout method which takes IResponder argument removed

SDK/backendlessAPI/Classes/UserService/UserService.h, SDK/backendlessAPI/Classes/UserService/UserService.m, SDK/ios/backendless/include/UserService.h, SDK/lib/backendless/include/UserService.h, SDK/osx/backendless/include/UserService.h
http://bugs.backendless.com/browse/BKNDLSS-14170
=> the restore password method which takes IResponder argument removed

Pods/Backendless.podspec, SDK/backendlessAPI/Classes/UserService/UserService.h, SDK/backendlessAPI/Classes/UserService/UserService.m, SDK/ios/backendless/include/UserService.h, SDK/lib/backendless/include/UserService.h, SDK/osx/backendless/include/UserService.h
http://bugs.backendless.com/browse/BKNDLSS-14172
=> The assignRole and unassignRole methods (sync and async) removed

SDK/backendlessAPI/Classes/UserService/UserService.h, SDK/backendlessAPI/Classes/UserService/UserService.m, SDK/ios/backendless/include/UserService.h, SDK/lib/backendless/include/UserService.h, SDK/osx/backendless/include/UserService.h
http://bugs.backendless.com/browse/BKNDLSS-14163
=> Bkndlss 14163new

SDK/backendlessAPI/Classes/UserService/UserService.h, SDK/backendlessAPI/Classes/UserService/UserService.m, SDK/ios/backendless/include/UserService.h, SDK/lib/backendless/include/UserService.h, SDK/osx/backendless/include/UserService.h
http://bugs.backendless.com/browse/BKNDLSS-14164
=> The easy twitter login methods fixed.

Pods/Backendless.podspec, SDK/backendlessAPI/Classes/Messaging/MessagingService.h, SDK/backendlessAPI/Classes/Messaging/MessagingService.m, SDK/ios/backendless/include/MessagingService.h, SDK/lib/backendless/include/MessagingService.h, SDK/osx/backendless/include/MessagingService.h
http://bugs.backendless.com/browse/BKNDLSS-14405
=> Bkndlss 14405

SDK/backendlessAPI/Classes/Files/FileService.h, SDK/backendlessAPI/Classes/Files/FileService.m, SDK/ios/backendless/include/FileService.h, SDK/lib/backendless/include/FileService.h, SDK/osx/backendless/include/FileService.h
http://bugs.backendless.com/browse/BKNDLSS-14463
http://bugs.backendless.com/browse/BKNDLSS-14464
http://bugs.backendless.com/browse/BKNDLSS-14465
http://bugs.backendless.com/browse/BKNDLSS-14466
http://bugs.backendless.com/browse/BKNDLSS-14467
http://bugs.backendless.com/browse/BKNDLSS-14468
http://bugs.backendless.com/browse/BKNDLSS-14469
=> The FileService class cleanup

SDK/backendlessAPI/Classes/Messaging/MessagingService.h, SDK/backendlessAPI/Classes/Messaging/MessagingService.m, SDK/ios/backendless/include/MessagingService.h, SDK/lib/backendless/include/MessagingService.h, SDK/osx/backendless/include/MessagingService.h
http://bugs.backendless.com/browse/BKNDLSS-14487
=> All methods that take IResponder as argument removed

SDK/backendlessAPI/Classes/Messaging/MessagingService.h, SDK/backendlessAPI/Classes/Messaging/MessagingService.m, SDK/backendlessAPI/Classes/Persistence/PersistenceService.m, SDK/ios/backendless/include/MessagingService.h, SDK/lib/backendless/include/MessagingService.h, SDK/osx/backendless/include/MessagingService.h
getEntityName method fixed to work correctly with BackendlessUser
=> File service improvement

SDK/backendlessAPI/Classes/Persistence/MapDrivenDataStore.m
http://bugs.backendless.com/browse/BKNDLSS-14551
=> find with where clause fixed for Dictionary/Map approach

Pods/Backendless.podspec
=> Podspec changed

SDK/backendlessAPI/backendlessAPI.xcodeproj/project.pbxproj
F9F0AF5B1CDBCAB500035C62 /* MessagingService.m in Sources */ = {isa = PBXBuildFile; fileRef = F9C3C058161AB6A500409FF2 /* MessagingService.m */; }; 
and 
F9F0AF5B1CDBCAB500035C62 /* MessagingService.m in Sources */
lines returned to .pbxproj
=> .pbxproj file fixed

SDK/backendlessAPI/Classes/Messaging/MessagingService.m
http://bugs.backendless.com/browse/BKNDLSS-14564
=> the RegisterDevice method now returns deviceId instead of registrationId

SDK/backendlessAPI/Classes/CacheService/CacheFactory.m, SDK/backendlessAPI/Classes/CacheService/CacheService.h, SDK/backendlessAPI/Classes/CacheService/CacheService.m, SDK/backendlessAPI/Classes/CacheService/ICacheService.h, SDK/ios/backendless/include/CacheService.h, SDK/ios/backendless/include/ICacheService.h, SDK/lib/backendless/include/CacheService.h, SDK/lib/backendless/include/ICacheService.h, SDK/osx/backendless/include/CacheService.h, SDK/osx/backendless/include/ICacheService.h
=> Caching API Improvement

SDK/backendlessAPI/Classes/Beacons/Presence.h, SDK/backendlessAPI/Classes/Beacons/Presence.m, SDK/backendlessAPI/Classes/CustomService/CustomService.h, SDK/backendlessAPI/Classes/CustomService/CustomService.m, SDK/backendlessAPI/Classes/Events/Events.h, SDK/backendlessAPI/Classes/Events/Events.m, SDK/backendlessAPI/Classes/Files/FileService.m, SDK/backendlessAPI/Classes/Geo/GeoService.m, SDK/backendlessAPI/Classes/Messaging/MessagingService.m, SDK/backendlessAPI/Classes/Persistence/DataPermission.h, SDK/backendlessAPI/Classes/Persistence/DataPermission.m, SDK/backendlessAPI/Classes/UserService/UserService.h, SDK/backendlessAPI/Classes/UserService/UserService.m, SDK/ios/backendless/include/CustomService.h, SDK/ios/backendless/include/DataPermission.h, SDK/ios/backendless/include/Events.h, SDK/ios/backendless/include/Presence.h, SDK/ios/backendless/include/UserService.h, SDK/lib/backendless/include/CustomService.h, SDK/lib/backendless/include/DataPermission.h, SDK/lib/backendless/include/Events.h, SDK/lib/backendless/include/Presence.h, SDK/lib/backendless/include/UserService.h, SDK/osx/backendless/include/CustomService.h, SDK/osx/backendless/include/DataPermission.h, SDK/osx/backendless/include/Events.h, SDK/osx/backendless/include/Presence.h, SDK/osx/backendless/include/UserService.h
All methods with responder (except Atomic Counters class) removed
=> Methods with responder cleanup

SDK/backendlessAPI/Classes/Beacons/BackendlessBeacon.h, SDK/backendlessAPI/Classes/Beacons/BeaconMonitoring.m, SDK/backendlessAPI/Classes/CustomService/CustomService.h, SDK/backendlessAPI/Classes/CustomService/CustomService.m, SDK/ios/backendless/include/BackendlessBeacon.h, SDK/ios/backendless/include/CustomService.h, SDK/lib/backendless/include/BackendlessBeacon.h, SDK/lib/backendless/include/CustomService.h, SDK/osx/backendless/include/BackendlessBeacon.h, SDK/osx/backendless/include/CustomService.h
version removed from hosted service invocation
=> BKNDLSS-14864

SDK/backendlessAPI/Classes/Messaging/DeliveryOptions.h, SDK/backendlessAPI/Classes/Messaging/DeliveryOptions.m, SDK/ios/backendless/include/DeliveryOptions.h, SDK/lib/backendless/include/DeliveryOptions.h, SDK/osx/backendless/include/DeliveryOptions.h
changed PublishPolicyEnum to support PUSH, PUBSUB and BOTH.
=> BKNDLSS-15032

SDK/backendlessAPI/Classes/UserService/UserService.m
findById called in UserService returns BackendlessUser
=> BKNDLSS-15082

SDK/backendlessAPI/Classes/UserService/BackendlessUser.h, SDK/backendlessAPI/Classes/UserService/BackendlessUser.m, SDK/backendlessAPI/Classes/UserService/UserService.h, SDK/backendlessAPI/Classes/UserService/UserService.m, SDK/ios/backendless/include/BackendlessUser.h, SDK/ios/backendless/include/UserService.h, SDK/lib/backendless/include/BackendlessUser.h, SDK/lib/backendless/include/UserService.h, SDK/osx/backendless/include/BackendlessUser.h, SDK/osx/backendless/include/UserService.h
Changed the getProperty method of BackendlessUser class to handle NSNull values
=> BKNDLSS-15163

SDK/backendlessAPI/Classes/UserService/UserService.h, SDK/backendlessAPI/Classes/UserService/UserService.m, SDK/backendlessAPI/Classes/weborb/Client/WeborbClient.m, SDK/ios/backendless/include/UserService.h, SDK/lib/backendless/include/UserService.h, SDK/osx/backendless/include/UserService.h
Issue when registering user and getting NSDictionary instead of BackendlessUser fixed
=> BKNDLSS-15165

SDK/backendlessAPI/Classes/Persistence/PersistenceService.m
=> Autoload relation loading fixed for the class approach

SDK/backendlessAPI/Classes/UserService/UserService.m
http://bugs.backendless.com/browse/BKNDLSS-15398
=> User token header fix

SDK/backendlessAPI/Classes/UserService/UserService.m
(connected to DataStoreFactory class mapping)
http://support.backendless.com/topic/cant-add-two-users-one-after-another
=> The error with user registration fixed

SDK/backendlessAPI/Classes/Persistence/LoadRelationsQueryBuilder.m, SDK/backendlessAPI/backendlessAPI.xcodeproj/project.pbxproj
=> ARC enabled for the LoadRelationsQueryBuilder class

SDK/backendlessAPI/Classes/Persistence/QueryOptionsBuilder.h, SDK/backendlessAPI/Classes/Persistence/QueryOptionsBuilder.m, SDK/ios/backendless/include/QueryOptionsBuilder.h, SDK/lib/backendless/include/QueryOptionsBuilder.h, SDK/osx/backendless/include/QueryOptionsBuilder.h
* relationsDepth type set to NSInteger
* getRelationsDepth method fixed
=> BKNDLSS-15715

SDK/backendlessAPI/Classes/DBManager.h, SDK/backendlessAPI/Classes/Persistence/DataQueryBuilder.h, SDK/backendlessAPI/Classes/Persistence/DataQueryBuilder.m, SDK/backendlessAPI/Classes/Persistence/MapDrivenDataStore.m, SDK/backendlessAPI/Classes/Persistence/OfflineDataStore.h, SDK/backendlessAPI/Classes/Persistence/PersistenceService.m, SDK/ios/backendless/include/DataQueryBuilder.h, SDK/lib/backendless/include/DataQueryBuilder.h, SDK/osx/backendless/include/DataQueryBuilder.h
=> 4.0.10 build

SDK/backendlessAPI/Classes/Persistence/BackendlessDataQuery.h, SDK/backendlessAPI/Classes/Persistence/BackendlessDataQuery.m, SDK/backendlessAPI/Classes/Persistence/DataQueryBuilder.h, SDK/backendlessAPI/Classes/Persistence/DataQueryBuilder.m, SDK/ios/backendless/include/BackendlessDataQuery.h, SDK/ios/backendless/include/DataQueryBuilder.h, SDK/lib/backendless/include/BackendlessDataQuery.h, SDK/lib/backendless/include/DataQueryBuilder.h, SDK/osx/backendless/include/BackendlessDataQuery.h, SDK/osx/backendless/include/DataQueryBuilder.h
=> refactoring of BackendlessDataQuery

SDK/backendlessAPI/Classes/UserService/UserService.m, SDK/backendlessAPI/backendlessAPI.xcodeproj/project.pbxproj
Support topic: http://support.backendless.com/topic/crash-on-facebook-logout
=> ARC enabled for User Service

SDK/backendlessAPI/Classes/UserService/UserService.h, SDK/backendlessAPI/Classes/UserService/UserService.m, SDK/ios/backendless/include/UserService.h, SDK/lib/backendless/include/UserService.h, SDK/osx/backendless/include/UserService.h
Added next methods to the UserService class:
`-(BackendlessUser *)loginWithTwitterSDK:(NSString *)authToken authTokenSecret:(NSString *)authTokenSecret fieldsMapping:(id)fieldsMapping;`
`-(void)loginWithTwitterSDK:(NSString *)authToken authTokenSecret:(NSString *)authTokenSecret fieldsMapping:(id)fieldsMapping response:(void(^)(BackendlessUser *))responseBlock error:(void(^)(Fault *))errorBlock;`
=> BKNDLSS-16146

SDK/backendlessAPI/Classes/Persistence/DataStoreFactory.m, SDK/backendlessAPI/Classes/Persistence/IDataStore.h, SDK/backendlessAPI/Classes/Persistence/MapDrivenDataStore.m, SDK/backendlessAPI/Classes/Persistence/PersistenceService.h, SDK/backendlessAPI/Classes/Persistence/PersistenceService.m, SDK/ios/backendless/include/IDataStore.h, SDK/ios/backendless/include/PersistenceService.h, SDK/lib/backendless/include/IDataStore.h, SDK/lib/backendless/include/PersistenceService.h, SDK/osx/backendless/include/IDataStore.h, SDK/osx/backendless/include/PersistenceService.h
BKNDLSS-15827 - bulkUpdate
BKNDLSS-15831 - bulkDelete
=> bulkUpdate and bulkDelete implemented

SDK/backendlessAPI/Classes/IO/AdaptResponder.h, SDK/backendlessAPI/Classes/IO/AdaptResponder.m, SDK/backendlessAPI/Classes/IO/Invoker.m, SDK/backendlessAPI/Classes/Messaging/MessagingService.h, SDK/backendlessAPI/Classes/Messaging/MessagingService.m, SDK/ios/backendless/include/AdaptResponder.h, SDK/ios/backendless/include/MessagingService.h, SDK/lib/backendless/include/AdaptResponder.h, SDK/lib/backendless/include/MessagingService.h, SDK/osx/backendless/include/AdaptResponder.h, SDK/osx/backendless/include/MessagingService.h
Changed the signature of Backendless.Messaging.sendEmail to return MessageStatus (BKNDLSS-12726). AdaptResponder fixed to handle fault correctly.
=> BKNDLSS-12726

Pods/Backendless-osx-SDK.podspec, Pods/Backendless.podspec, SDK/backendlessAPI/Classes/Persistence/DataStoreFactory.m
The remove method of DataStoreFactory fixed and returns fault when trying to access the table that doesn't exist
=> remove method fixed

SDK/backendlessAPI/Classes/Persistence/DataStoreFactory.m, SDK/backendlessAPI/Classes/Persistence/PersistenceAdapter/AdapterFactory.h, SDK/backendlessAPI/Classes/Persistence/PersistenceAdapter/AdapterFactory.m, SDK/backendlessAPI/Classes/Persistence/PersistenceAdapter/BackendlessUserAdapter.h, SDK/backendlessAPI/Classes/Persistence/PersistenceAdapter/BackendlessUserAdapter.m, SDK/backendlessAPI/Classes/Persistence/PersistenceService.m, SDK/backendlessAPI/Classes/UserService/BackendlessUser.m, SDK/backendlessAPI/Classes/UserService/UserService.m, SDK/backendlessAPI/backendlessAPI.xcodeproj/project.pbxproj, SDK/ios/backendless/include/AdapterFactory.h, SDK/ios/backendless/include/BackendlessUserAdapter.h, SDK/lib/backendless/include/AdapterFactory.h, SDK/lib/backendless/include/BackendlessUserAdapter.h, SDK/osx/backendless/include/AdapterFactory.h, SDK/osx/backendless/include/BackendlessUserAdapter.h
AdapterFactory and BackendlessUserAdapter classes added.
BKNDLSS-16760
=> BackendlessUser adaptation fixed

SDK/backendless.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, SDK/backendlessAPI/Classes/Persistence/DataStoreFactory.m, SDK/backendlessAPI/Classes/Persistence/IDataStore.h, SDK/backendlessAPI/Classes/Persistence/MapDrivenDataStore.m, SDK/backendlessAPI/Classes/Persistence/PersistenceService.h, SDK/backendlessAPI/Classes/Persistence/PersistenceService.m, SDK/backendlessAPI/backendlessAPI.xcodeproj/project.pbxproj, SDK/backendlessAPI/backendlessAPI.xcodeproj/xcshareddata/xcschemes/backendless-dev-fat.xcscheme, SDK/backendlessAPI/backendlessAPI.xcodeproj/xcshareddata/xcschemes/backendless-device.xcscheme, SDK/backendlessAPI/backendlessAPI.xcodeproj/xcshareddata/xcschemes/backendless-fat.xcscheme, SDK/backendlessAPI/backendlessAPI.xcodeproj/xcshareddata/xcschemes/backendless-mac.xcscheme, SDK/backendlessAPI/backendlessAPI.xcodeproj/xcshareddata/xcschemes/backendless-simulator.xcscheme, SDK/backendlessAPI/backendlessAPI.xcodeproj/xcshareddata/xcschemes/bkndlss-device.xcscheme, SDK/backendlessAPI/backendlessAPI.xcodeproj/xcshareddata/xcschemes/bkndlss-simulator.xcscheme, SDK/ios/backendless/include/IDataStore.h, SDK/ios/backendless/include/PersistenceService.h, SDK/lib/backendless/include/IDataStore.h, SDK/lib/backendless/include/PersistenceService.h, SDK/osx/backendless/include/IDataStore.h, SDK/osx/backendless/include/PersistenceService.h
=> Bulk create added

SDK/backendlessAPI/Classes/weborb/Client/HttpEngine.m, SDK/backendlessAPI/backendlessAPI.xcodeproj/project.pbxproj
NSURLConnection deprrecated methods fixed
=> HttpEngine deprecated methods fixed

SDK/backendlessAPI/Classes/RT/Data/EventHandler.h, SDK/backendlessAPI/Classes/RT/Data/EventHandler.m, SDK/backendlessAPI/Classes/RT/RTClient.m, SDK/ios/backendless/include/EventHandler.h, SDK/lib/backendless/include/EventHandler.h, SDK/osx/backendless/include/EventHandler.h, SDK/tvos/backendless/include/EventHandler.h, SDK/watchos/backendless/include/EventHandler.h
Missing bulk create listener methods added in RT
=> Bkndlss 16856

SDK/backendlessAPI/Classes/RT/Data/EventHandler.m, SDK/backendlessAPI/Classes/RT/RTClient.m, SDK/backendlessAPI/Classes/weborb/Reader/AnonymousObject.m
http://bugs.backendless.com/browse/BKNDLSS-17553
=> Loading all user properties of a GeoPoint's linked user object fixed

SDK/backendlessAPI/backendlessAPI.xcodeproj/project.pbxproj, SDK/tvos/backendless/include/UserDefaultsHelper.h, SDK/watchos/backendless/include/UserDefaultsHelper.h
=> UserDefaultsHelper class added to the tvOS and watchOS builds

SDK/backendlessAPI/Classes/Messaging/BackendlessPushHelper.m
Inline reply "textInputPlaceholder" and "inputButtonTitle" fixed when values are not set in console
=> Inline reply fixed

SDK/backendlessAPI/Classes/Files/FileService.h, SDK/backendlessAPI/Classes/Files/FileService.m, SDK/backendlessAPI/backendlessAPI.xcodeproj/project.pbxproj, SDK/ios/backendless/include/FileService.h, SDK/lib/backendless/include/FileService.h, SDK/osx/backendless/include/FileService.h, SDK/tvos/backendless/include/FileService.h, SDK/watchos/backendless/include/FileService.h
http://bugs.backendless.com/browse/BKNDLSS-17960
* ARC added to FileService
* UploadFile methods added
=> UploadFile

CHANGELOG.md, SDK/backendlessAPI/Classes/Persistence/LoadRelationsQueryBuilder.h, SDK/backendlessAPI/Classes/Persistence/LoadRelationsQueryBuilder.m, SDK/backendlessAPI/backendlessAPI.xcodeproj/project.pbxproj, SDK/ios/backendless/include/LoadRelationsQueryBuilder.h, SDK/lib/backendless/include/LoadRelationsQueryBuilder.h, SDK/osx/backendless/include/LoadRelationsQueryBuilder.h, SDK/tvos/backendless/include/LoadRelationsQueryBuilder.h, SDK/watchos/backendless/include/LoadRelationsQueryBuilder.h
added support of sortBy and properties for LoadRelationsQueryBuilder
=> BKNDLSS-18028

SDK/backendlessAPI/Classes/Messaging/EmailEnvelope.m, SDK/backendlessAPI/Classes/Messaging/MessagingService.m
* EmailEnvelope to, cc, bcc default values = nil, additional checks added
=> EmailEnvelope fixed

CHANGELOG.md, Pods/Backendless.podspec, SDK/Podfile.lock, SDK/backendless.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings, SDK/backendlessAPI/Classes/Messaging/MessagingService.m, SDK/backendlessAPI/backendlessAPI.xcodeproj/project.pbxproj, SDK/backendlessAPI/backendlessAPI.xcodeproj/xcshareddata/xcschemes/backendless-device.xcscheme, SDK/backendlessAPI/backendlessAPI.xcodeproj/xcshareddata/xcschemes/backendless-fat.xcscheme, SDK/backendlessAPI/backendlessAPI.xcodeproj/xcshareddata/xcschemes/backendless-mac.xcscheme, SDK/backendlessAPI/backendlessAPI.xcodeproj/xcshareddata/xcschemes/backendless-simulator.xcscheme, SDK/backendlessAPI/backendlessAPI.xcodeproj/xcshareddata/xcschemes/backendless-tv-device.xcscheme, SDK/backendlessAPI/backendlessAPI.xcodeproj/xcshareddata/xcschemes/backendless-tv-simulator.xcscheme, SDK/backendlessAPI/backendlessAPI.xcodeproj/xcshareddata/xcschemes/backendless-watch-device.xcscheme, SDK/backendlessAPI/backendlessAPI.xcodeproj/xcshareddata/xcschemes/backendless-watch-simulator.xcscheme, SDK/backendlessAPI/backendlessAPI.xcodeproj/xcshareddata/xcschemes/bkndlss-device.xcscheme, SDK/backendlessAPI/backendlessAPI.xcodeproj/xcshareddata/xcschemes/bkndlss-simulator.xcscheme
=> fixed device registration for iOS 13
